In [1]:
import pandas as pd

The goal for this code is to create a dataframe from an xls file from the brazilian infrastructure department, which holds information from hydroeletrical powerplant water levels across the country. In order to work with nested loops, dictionary format will be easier to handle.

In [ ]:
sheets_dict = pd.read_excel('ACOMPH_12.05.2020.xls', sheet_name=None)

In [26]:
all_sheets = []


df_full_complete = pd.DataFrame()


# Loop nas guias (regiao)
for regiao, sheet in sheets_dict.items():

    # Pegando os nomes dos locais nas guias
    locais = sheet.iloc[0,1:].dropna()
    
    #tamanho do intervalo de cada local
    BLOCK_SIZE= 8

    df_full_region = pd.DataFrame()
    
    # O loop interno que vai nas regiões(abas) e retira os dados dos locais
    for i, local in enumerate(locais):

        # BASE é o primeiro indice da coluna do bloco em analise...
        base = 1 + BLOCK_SIZE * i
        col_start, col_end = base, base + 8
        df_aux = sheet.iloc[4:34, col_start:col_end]

        
        col_names = ["Lido", "Consol", "Lido", "Consol", "Lido", "Consol", "icr_consol", "nat_consol"]

        df_aux.columns = col_names

        df_aux.reset_index(inplace=True, drop=True)

        df_aux['local'] = local
        df_aux['regiao'] = regiao
        df_aux['data'] = sheet.iloc[4:34,0].reset_index(drop=True)
        
        df_full_region = pd.concat([df_full_region, df_aux], axis=0)
    
    
    # Saindo do loop da regiao, ele vai entrar, ele insere o bloco no full
    
    df_full_complete = pd.concat([df_full_complete, df_full_region], axis=0)

In [27]:
df_full_complete.head(40)

,Lido,Consol,Lido,Consol,Lido,Consol,icr_consol,nat_consol,local,regiao,data
0,912.52,912.49,54,54,107,94.509259,99.500744,99.500744,CAMARGOS,Grande,2020-04-12
1,912.56,912.54,54,54,93,94.509259,103.38407,103.38407,CAMARGOS,Grande,2020-04-13
2,912.52,912.48,142,142,99,93.388889,98.10537,98.10537,CAMARGOS,Grande,2020-04-14
3,912.51,912.47,105,105,104,96.898148,92.843218,92.843218,CAMARGOS,Grande,2020-04-15
4,912.51,912.47,92,92,93,92,90.778331,90.778331,CAMARGOS,Grande,2020-04-16
5,912.51,912.48,83,83,91,91.101852,88.991204,88.991204,CAMARGOS,Grande,2020-04-17
6,912.54,912.51,62,62,84,86.305556,87.017476,87.017476,CAMARGOS,Grande,2020-04-18
7,912.57,912.54,60,60,81,84.305556,84.960835,84.960835,CAMARGOS,Grande,2020-04-19
8,912.59,912.57,60,60,78,84.305556,83.489887,83.489887,CAMARGOS,Grande,2020-04-20
9,912.63,912.61,48,48,80,80.407407,82.232626,82.232626,CAMARGOS,Grande,2020-04-21
10,912.66,912.65,46,46,75,78.407407,81.053947,81.053947,CAMARGOS,Grande,2020-04-22
11,912.69,912.68,58,58,75,82.305556,79.847079,79.847079,CAMARGOS,Grande,2020-04-23
12,912.71,912.7,59,59,75,75.203704,78.761306,78.761306,CAMARGOS,Grande,2020-04-24
13,912.72,912.72,57,57,73,73.203704,77.772651,77.772651,CAMARGOS,Grande,2020-04-25
14,912.74,912.74,56,56,72,72.203704,76.380058,76.380058,CAMARGOS,Grande,2020-04-26
15,912.76,912.76,57,57,74,73.203704,75.136922,75.136922,CAMARGOS,Grande,2020-04-27
16,912.77,912.77,63,63,69,71.101852,74.200961,74.200961,CAMARGOS,Grande,2020-04-28
17,912.77,912.77,69,69,69,69,73.521252,73.521252,CAMARGOS,Grande,2020-04-29
18,912.77,912.77,69,69,69,69,72.432417,72.432417,CAMARGOS,Grande,2020-04-30
19,912.77,912.77,69,69,69,69,71.105103,71.105103,CAMARGOS,Grande,2020-05-01
20,912.77,912.77,69,69,68,69,70.525061,70.525061,CAMARGOS,Grande,2020-05-02
21,912.77,912.77,69,69,70,69,69.73104,69.73104,CAMARGOS,Grande,2020-05-03
22,912.77,912.76,69,69,69,60.898148,68.805304,68.805304,CAMARGOS,Grande,2020-05-04
23,912.77,912.77,60,60,60,68.101852,68.298582,68.298582,CAMARGOS,Grande,2020-05-05
24,912.78,912.78,57,57,68,65.101852,67.590558,67.590558,CAMARGOS,Grande,2020-05-06
25,912.79,912.79,57,57,69,65.101852,67.03477,67.03477,CAMARGOS,Grande,2020-05-07
26,912.8,912.8,57,57,65,65.101852,66.97302,66.97302,CAMARGOS,Grande,2020-05-08
27,912.81,912.81,58,58,66,66.101852,66.110767,66.110767,CAMARGOS,Grande,2020-05-09
28,912.82,912.82,58,58,66,66.101852,64.977018,64.977018,CAMARGOS,Grande,2020-05-10
29,912.82,912.82,58,58,58,58,64.577885,64.577885,CAMARGOS,Grande,2020-05-11
0,807.87,807.9,250,250,247,242.12963,186.771578,284.256808,FUNIL-GRANDE,Grande,2020-04-12
1,807.89,807.9,244,244,251,244,185.928748,287.209349,FUNIL-GRANDE,Grande,2020-04-13
2,807.94,807.94,267,267,282,282.740741,183.488906,284.453571,FUNIL-GRANDE,Grande,2020-04-14
3,807.89,807.8,359,359,342,303.907407,182.644665,278.338215,FUNIL-GRANDE,Grande,2020-04-15
4,807.86,807.8,305,305,294,305,179.411348,271.308159,FUNIL-GRANDE,Grande,2020-04-16
5,807.9,807.8,255,255,270,255,173.493062,263.452293,FUNIL-GRANDE,Grande,2020-04-17
6,807.91,807.8,217,217,229,217,165.59327,253.679849,FUNIL-GRANDE,Grande,2020-04-18
7,807.93,807.82,197,197,200,204.87037,157.687597,243.762446,FUNIL-GRANDE,Grande,2020-04-19
8,807.94,807.88,184,184,187,207.611111,152.00578,236.29243,FUNIL-GRANDE,Grande,2020-04-20
9,807.91,807.87,198,198,189,194.064815,147.693946,230.607588,FUNIL-GRANDE,Grande,2020-04-21

Ajustes finais no df

In [30]:
df_full_complete.drop(['Lido', 'Consol'], axis=1, inplace=True)
df_full_complete

   icr_consol   nat_consol           local    regiao       data
0   99.500744    99.500744        CAMARGOS    Grande 2020-04-12
1   103.38407    103.38407        CAMARGOS    Grande 2020-04-13
2    98.10537     98.10537        CAMARGOS    Grande 2020-04-14
3   92.843218    92.843218        CAMARGOS    Grande 2020-04-15
4   90.778331    90.778331        CAMARGOS    Grande 2020-04-16
..        ...          ...             ...       ...        ...
25   21.23312  2648.110363  FERREIRA GOMES  Araguari 2020-05-07
26  21.609783  2693.523743  FERREIRA GOMES  Araguari 2020-05-08
27   22.35919  2779.754411  FERREIRA GOMES  Araguari 2020-05-09
28  22.927269  2854.030427  FERREIRA GOMES  Araguari 2020-05-10
29  23.285031  2903.065788  FERREIRA GOMES  Araguari 2020-05-11

[4440 rows x 5 columns]

In [31]:
new_cols = ["data","local","regiao","icr_consol","nat_consol"]
df_full_complete=df_full_complete[new_cols]
df_full_complete

         data           local    regiao icr_consol   nat_consol
0  2020-04-12        CAMARGOS    Grande  99.500744    99.500744
1  2020-04-13        CAMARGOS    Grande  103.38407    103.38407
2  2020-04-14        CAMARGOS    Grande   98.10537     98.10537
3  2020-04-15        CAMARGOS    Grande  92.843218    92.843218
4  2020-04-16        CAMARGOS    Grande  90.778331    90.778331
..        ...             ...       ...        ...          ...
25 2020-05-07  FERREIRA GOMES  Araguari   21.23312  2648.110363
26 2020-05-08  FERREIRA GOMES  Araguari  21.609783  2693.523743
27 2020-05-09  FERREIRA GOMES  Araguari   22.35919  2779.754411
28 2020-05-10  FERREIRA GOMES  Araguari  22.927269  2854.030427
29 2020-05-11  FERREIRA GOMES  Araguari  23.285031  2903.065788

[4440 rows x 5 columns]

As we can see, the xls file compromises any data science use for this data. I put this data in a "long" or "tide" format, after all coding. We can organize this data also in a SQL using some cloud platform.